title: QMK Configurator
email: yanfali@gmail.com
show_downloads: true
description: QMK for potatoes - an open source configurator for QMK Firmware (only the AVR boards right now)
baseurl: "/qmk_configurator"
url: "http://yanfali.github.io"
github_username: yanfali
repository: yanfali/qmk_configurator
theme: jekyll-theme-minimal
